# Generated by Django 5.1.7 on 2025-06-04 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('waste_count', models.IntegerField(default=0)),
                ('no_waste_count', models.IntegerField(default=0)),
                ('waste_ratio', models.FloatField(default=0.0)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
